version: "3.7"
# definição dos serviços do stack
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    networks:
    - network_swarm_databases
    - network_swarm_public
    environment:
    - PGADMIN_DEFAULT_EMAIL=suporte@ip2sec.com.br
    - PGADMIN_DEFAULT_PASSWORD=Vp0qkuN2rdTcRKW93R5ika
    volumes:
    - pgadmin_data:/var/lib/pgadmin
    ports:
    - 4010:80
    links:
    - postgres
    deploy:
      # configura o modo de deploy do serviço do postgres
      mode: replicated
      # configura o numero de replicas do serviço do postgres (1 é o padrão)
      replicas: 1
      # Define a estratégia de deploy do serviço
      placement:
        constraints:
        # você pode definir aonde o serviço irá rodar (worker ou manager)
        # aqui você pode definir que quer que rode no manager
        - node.role == manager
        # ou pode escolher um node específico pelo hostname
        #- node.hostname == database01
        #resources:
        # configura os limites de recursos do serviço do postgres
        #limits:
        # configura o limite de CPU do serviço do postgres
        #  cpus: "1"
        # configura o limite de memória do serviço do postgres
        #  memory: 2048M
volumes:
  pgadmin_data:
    external: true
    name: pgadmin_data

networks:
  network_swarm_databases:
    external: true
    name: network_swarm_databases
  network_swarm_public:
    external: true
    name: network_swarm_public
